DROP TABLE BOARD ;--게시판 삭제

CREATE TABLE BOARD(
 BOARD_NO NUMBER CONSTRAINT PK_BOARD_BOARD_NO PRIMARY KEY,
 MEM_ID VARCHAR2(100),
 CONSTRAINT FK_BOARD_MEM_ID FOREIGN KEY (MEM_ID)
	REFERENCES MEMBERS(MEM_ID) ON DELETE CASCADE,
BOARD_TITLE VARCHAR2(100) NOT NULL,
BOARD_LIKE NUMBER,
BOARD_CONTENT VARCHAR2(4000),
BOARD_DATE DATE,
BOARD_PICTURE VARCHAR2(1000) -- BOARD_PFILE를 삭제하고 PICTURE VARCHAR2(1000)컬름을 BOARD테이블에 추가
);

ALTER TABLE BOARD RENAME COLUMN PICTURE to BOARD_PICTURE;

create sequence BOARD_NO_SEQ start with 1
minvalue 1 maxvalue 1000000 CYCLE; 

drop sequence BOARD_NO_SEQ ;--- 시퀀스 삭제

SELECT* FROM BOARD;

INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요1',10,'오늘은 온몸이 아픈날이네',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요2',9,'오늘은 온몸이 아픈날이네1',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요3',8,'오늘은 온몸이 아픈날이네2',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요4',7,'오늘은 온몸이 아픈날이네3',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요5',6,'오늘은 온몸이 아픈날이네4',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요6',5,'오늘은 온몸이 아픈날이네5',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요7',4,'오늘은 온몸이 아픈날이네6',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요8',3,'오늘은 온몸이 아픈날이네7',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요9',3,'오늘은 온몸이 아픈날이네8',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요10',3,'오늘은 온몸이 아픈날이네9',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요11',3,'오늘은 온몸이 아픈날이네10',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요12',3,'오늘은 온몸이 아픈날이네11',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요13',3,'오늘은 온몸이 아픈날이네7',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요14',3,'오늘은 온몸이 아픈날이네8',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요15',3,'오늘은 온몸이 아픈날이네9',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요16',3,'오늘은 온몸이 아픈날이네10',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요17',3,'오늘은 온몸이 아픈날이네11',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요1',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'apple.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요2',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'banana.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요3',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'dog.jpg');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요4',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'Elvis.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요5',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'Elvis1.jpg');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요6',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'Elvis2.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요7',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'mango.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요8',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'myWorld.JPG');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요9',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'apple.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요10',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'banana.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요11',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'dog.jpg');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요12',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'Elvis.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요13',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'Elvis1.jpg');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요14',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'mango.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요15',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'myWorld.JPG');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요16',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'apple.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요17',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'banana.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요18',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'dog.jpg');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요19',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'Elvis.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요20',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'Elvis1.jpg');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요21',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'Elvis2.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요22',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'mango.png');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요23',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'myWorld.JPG');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIMAN','안녕하세요23',3,'오늘은 온몸이 아픈날이네12',SYSDATE, 'emotional1.jpg');

INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'STAFF','오늘 뭐하지',5,'뭐할까요용옹',SYSDATE, null);
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'HIGIRL','오늘의 반찬',4,'고기마싯당', SYSDATE, 'myWorld.JPG');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL,'MASTER','다들 뭐하고 지내',3,'나는 굴러다녀 ',SYSDATE, null);

-- 게시글 LIST 페이징
select * 
FROM (select rownum num, BOARD_TITLE, BOARD_DATE, BOARD_NO 
FROM (select * from BOARD b, MEMBERS m
WHERE b.MEM_ID = m.MEM_ID AND m.MEM_ID = 'HIMAN' 
AND BOARD_PICTURE IS NULL
order by BOARD_NO desc)) 
where num between 1 and 5 ;
-- 게시글 LIST 데이터 개수
SELECT count(*) 
FROM BOARD
WHERE MEM_ID = 'HIMAN'
AND BOARD_PICTURE IS NULL;

-- 사진 게시글 LIST 페이징
select * 
FROM (select rownum num, BOARD_NO, BOARD_PICTURE
FROM (select * from BOARD b, MEMBERS m
WHERE b.MEM_ID = m.MEM_ID AND m.MEM_ID = 'HIMAN' 
AND BOARD_PICTURE IS NOT NULL
order by BOARD_NO desc)) 
where num between 1 and 30 ;
-- 사진 게시글 LIST 데이터 개수
SELECT count(*) 
FROM BOARD
WHERE MEM_ID = 'HIMAN'
AND BOARD_PICTURE IS NOT NULL;

-- 게시글 상세 조회
SELECT B.BOARD_TITLE, B.BOARD_LIKE, 
B.BOARD_CONTENT,B.BOARD_DATE, M.MEM_NAME, B.BOARD_PICTURE
FROM MEMBERS M , BOARD B
WHERE B.MEM_ID=M.MEM_ID 
AND B.BOARD_NO =12;

SELECT M.MEM_ID,B.BOARD_TITLE
,B.BOARD_CONTENT,B.BOARD_LIKE
E,B.BOARD_DATE,
B.BOARD_NO ,L.PICTURE
FROM MEMBERS M , BOARD B,
BOARD_PFILE L
WHERE B.MEM_ID=M.MEM_ID AND
B.BOARD_NO = L.BOARD_NO
AND B.BOARD_NO =7;

DELETE FROM BOARD
WHERE BOARD_NO = 69;
---------------------------------------------------------------------
--좋아요 --
DROP TABLE BOARD_LIKE;--게시판 삭제

CREATE TABLE BOARD_LIKE(
 BOARD_NO NUMBER,
 CONSTRAINT FK_BOARD_LIKE_BOARD_NO FOREIGN KEY (BOARD_NO)
	REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
MEM_ID VARCHAR2(100),
CONSTRAINT FK_BOARD_LIKE_MEM_ID FOREIGN KEY (MEM_ID)
	REFERENCES MEMBERS(MEM_ID) ON DELETE CASCADE
);

SELECT* FROM BOARD_LIKE ;

INSERT INTO BOARD_LIKE VALUES (4,'HIMAN');
INSERT INTO BOARD_LIKE VALUES (4,'STAFF');
INSERT INTO BOARD_LIKE VALUES (5,'STAFF');
INSERT INTO BOARD_LIKE VALUES (6,'HIGIRL');
INSERT INTO BOARD_LIKE VALUES (7,'MASTER');

SELECT M.MEM_ID,B.BOARD_TITLE,B.BOARD_CONTENT,B.BOARD_LIKE,L.MEM_ID,B.BOARD_NO
FROM MEMBERS M , BOARD B, BOARD_LIKE L
WHERE B.MEM_ID=M.MEM_ID AND B.BOARD_NO = L.BOARD_NO --게시글 내용 , 게시글 좋아요한 갯수 및 좋아요 한 ID 

SELECT L.MEM_ID FROM BOARD_LIKE  L ,BOARD B WHERE L.BOARD_NO =B.BOARD_NO 



---------------------------------------------------------------
--게시글 사진 파일 ------------------------------------------------

CREATE TABLE BOARD_PFILE(
 BOARD_NO NUMBER,
 CONSTRAINT BOARD_PFILE_BOARD_NO FOREIGN KEY (BOARD_NO)
	REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
 PICTURE VARCHAR2(1000)
);
DROP TABLE BOARD_PFILE ;--게시판 삭제
INSERT INTO BOARD_PFILE VALUES(4,'FLOWER.IMG');
INSERT INTO BOARD_PFILE VALUES(4,'FLOWER2.IMG');
INSERT INTO BOARD_PFILE VALUES(5,'NOTEPAD.IMG');
INSERT INTO BOARD_PFILE VALUES(6,'COMPUTER.IMG');
INSERT INTO BOARD_PFILE VALUES(7,'COMPUTER.IMG');
INSERT INTO BOARD_PFILE VALUES(7,'img/dog.jpg');

SELECT * FROM BOARD_PFILE;


SELECT M.MEM_ID,B.BOARD_TITLE,B.BOARD_CONTENT,B.BOARD_LIKE, B.BOARD_NO ,L.PICTURE
FROM MEMBERS M , BOARD B, BOARD_PFILE L 
WHERE B.MEM_ID=M.MEM_ID AND B.BOARD_NO = L.BOARD_NO 
AND B.BOARD_NO=4--사진 포함 게시글 


DROP TABLE BOARD ;--게시판 삭제

