DROP TABLE COMMENTS ;--게시판 삭제

CREATE TABLE COMMENTS(
COM_NO NUMBER,
BOARD_NO NUMBER,
CONSTRAINT FK_COMMENTS_BOARD_NO FOREIGN KEY (BOARD_NO)
REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,	
GBOOK_NO NUMBER,
CONSTRAINT FK_COMMENTS_GBOOK_NO FOREIGN KEY (GBOOK_NO)
REFERENCES GUESTBOOK(GBOOK_NO) ON DELETE CASCADE,	
MEM_ID VARCHAR2(100),
CONSTRAINT FK_COMMENTS_MEM_ID FOREIGN KEY (MEM_ID)
REFERENCES MEMBERS(MEM_ID) ON DELETE CASCADE,
COM_CONTENT VARCHAR2(1000) NOT NULL,
COM_DATE DATE
);

CREATE SEQUENCE COM_NO_SEQ 
START WITH 1
MINVALUE 1
maxvalue 1000000 CYCLE;

drop sequence COM_NO_SEQ ;--- 시퀀스 삭제

INSERT INTO COMMENTS(COM_NO, BOARD_NO, MEM_ID, COM_CONTENT, COM_DATE) 
values(COM_NO_SEQ.NEXTVAL, 81, 'HIMAN', 'ㅋㅋㅋㅋㅋ',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 68, null, 'HIGIRL', 'ㅎㅎㅎㅎㅎ',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 68, null, 'DOOBOO', '안녕!',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 68, null, 'GOODMAN', '하이루!',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 71, null, 'HIGIRL', '중2병이야?',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 71, null, 'DOOBOO', '웃기넼ㅋㅋㅋ',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 71, null, 'HIGIRL', '만만하게 보니까??ㅋㅋ',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 71, null, 'GOODMAN', '하이루!',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 62, null, 'GOODMAN', '하이루!',sysdate);
INSERT INTO COMMENTS values(COM_NO_SEQ.NEXTVAL, 81, null, 'GOODMAN', '하이루!',sysdate);

SELECT * FROM MEMBERS;  -- MEMBERS 조회

SELECT * FROM COMMENTS;

-- 게시판 댓글 조회
SELECT COM_CONTENT, COM_DATE, m.MEM_NAME 
FROM COMMENTS c, MEMBERS m
WHERE c.MEM_ID = m.MEM_ID AND BOARD_NO = 81
ORDER BY COM_DATE;
