CREATE TABLE GUESTBOOK(
GBOOK_NO NUMBER CONSTRAINT PK_GUESTBOOK_GBOOK_NO PRIMARY KEY,
HOME_NO NUMBER,
CONSTRAINT FK_GUESTBOOK_HOME_NO FOREIGN KEY (HOME_NO)
	REFERENCES MYHOME(HOME_NO) ON DELETE CASCADE,
MEM_ID VARCHAR2(100),
CONSTRAINT FK_GUESTBOOK_MEM_ID FOREIGN KEY (MEM_ID)
REFERENCES MEMBERS(MEM_ID ) ON DELETE CASCADE,
GB_CONTENT VARCHAR2(2000) NOT NULL,
GB_DATE DATE,
GB_CONSTRAINT VARCHAR2(10)NOT NULL
);

SELECT * FROM GUESTBOOK 