-- 순서  : members => follow => board =>board_like or board_pfile => deco =>myhome => guestbook =>comment 다른 방법 있지만 이 순서로  오류는 없습니다~


CREATE TABLE members (
 MEM_ID VARCHAR2(100) CONSTRAINT PK_MEMBERS_MEM_ID PRIMARY KEY,
 MEM_PASS VARCHAR2(50) NOT NULL,
 MEM_NAME VARCHAR2(50) NOT NULL,
 MEM_BIRTH DATE,
 MEM_PNUMBER VARCHAR2(50) NOT NULL,
 MEM_EMAIL VARCHAR2(100) NOT NULL,
 MEM_ADDRESS VARCHAR2(100),
 MEM_SIGN_UP DATE,
 GENDER VARCHAR2(10),
 MEM_AUTH VARCHAR(10)
);
SELECT * FROM MEMBERS;  -- MEMBERS 조회
DROP TABLE MEMBERS; --MEMBERS 테이블 삭제
DELETE FROM members WHERE mem_id= 'HIMAN'; -- 회원 탈퇴시 사용할 쿼리 (다른 테이블에 MEM_ID FK 가지고있어도 정상 실행 되야함)


INSERT INTO MEMBERS VALUES('HIMAN','7777','홍길동','1995-09-28','010-7856-1123','DODO@DAUM.NET','서울 신림',SYSDATE,'남','NORMAL');
INSERT INTO MEMBERS VALUES('HIGIRL','21277','김국수','2000-03-21','010-8952-1235','HONG@DAUM.NET','서울 강동구',SYSDATE,'여','NORMAL');
INSERT INTO MEMBERS VALUES('MASTER','1111','관리자','1995-05-21','010-1234-5678','SIST01@NAVER.COM','서울 강남구',SYSDATE,'남','MASTER');
INSERT INTO MEMBERS VALUES('STAFF','11231','스태프','1994-06-20','010-9876-5678','SIST02@NAVER.COM','서울 강남구',SYSDATE,'여','STAFF');
INSERT INTO MEMBERS VALUES('DOOBOO','1521','두부','2000-07-20','010-4523-8612','DOOBOO@NAVER.COM','서울 광진구',SYSDATE,'여','NORMAL');
INSERT INTO MEMBERS VALUES('GOODMAN','9811','굳맨','1998-07-20','010-5221-1234','GOODBOY@NAVER.COM','서울 강북구',SYSDATE,'여','NORMAL');
INSERT INTO MEMBERS VALUES('SIST01','2211','쌍용','1999-12-20','010-9853-1457','SSANGYOUNG@NAVER.COM','서울 중구',SYSDATE,'여','NORMAL');

   


--ON DELETE CASCADE => MEM_ID를 FK로 가지고 있어 회원 탈퇴(MEM_ID 삭제)시에  오류가 발생할 수 있어 추가
CREATE TABLE FOLLOW(
	MEM_ID VARCHAR2(100) NOT NULL,
	FOLLOWING_ID VARCHAR2(100),
	CONSTRAINT FK_FOLLOWE_MEM_ID FOREIGN KEY (MEM_ID)
	REFERENCES MEMBERS(MEM_ID) ON DELETE CASCADE,			
	CONSTRAINT FK_FOLLOWING_ID FOREIGN KEY (FOLLOWING_ID)
	REFERENCES MEMBERS(MEM_ID) ON DELETE CASCADE
);

SELECT *FROM FOLLOW ; --FOLLOW 조회

DROP TABLE FOLLOW ; -- FOLLOW 테이블 삭제 

INSERT INTO FOLLOW VALUES ('HIMAN','STAFF');
INSERT INTO FOLLOW VALUES ('HIMAN','HIGIRL');
INSERT INTO FOLLOW VALUES ('HIMAN','MASTER');
INSERT INTO FOLLOW VALUES ('HIMAN','DOOBOO');
INSERT INTO FOLLOW VALUES ('HIMAN','GOODMAN');


INSERT INTO FOLLOW VALUES ('STAFF','HIMAN');
INSERT INTO FOLLOW VALUES ('HIGIRL','HIMAN');
INSERT INTO FOLLOW VALUES ('MASTER','HIMAN');
INSERT INTO FOLLOW VALUES ('DOOBOO','HIMAN');
INSERT INTO FOLLOW VALUES ('GOODMAN','HIMAN');
INSERT INTO FOLLOW VALUES ('SIST01','HIMAN');

SELECT m.mem_name, f.mem_id, m.MEM_EMAIL FROM FOLLOW f ,MEMBERS M
WHERE F.MEM_ID =M.MEM_ID AND m.MEM_id ='HIMAN' AND ; -- HIMAN 로그인한  ID 의 팔로잉 목록

SELECT m.mem_name, m.mem_id, m.MEM_EMAIL FROM FOLLOW f ,MEMBERS M
WHERE F.MEM_ID =M.MEM_ID AND '검색조건'(m.MEM_ID OR m.mem_name) ='검색어';-- HIMAN 로그인한  ID 의 팔로잉 목록 검색조건 처리

SELECT m.mem_name, f.mem_id, m.MEM_EMAIL FROM FOLLOW f ,MEMBERS M
WHERE F.FOLLOWING_ID ='HIMAN' AND M.MEM_ID =F.MEM_ID; --HIMAN 을 팔로우한 목록

SELECT m.mem_name, f.mem_id, m.MEM_EMAIL FROM FOLLOW f ,MEMBERS M
WHERE F.FOLLOWING_ID ='HIMAN' AND '검색조건'(m.MEM_ID OR m.mem_name) ='검색어'; --HIMAN 을 팔로우한 목록  검색조건 처리


SELECT MEM_NAME, MEM_ID, MEM_EMAIL FROM MEMBERS m WHERE MEM_ID IN (
SELECT FOLLOWING_ID FROM FOLLOW 
WHERE MEM_ID ='HIMAN'); -- HIMAN 로그인한  ID 의 팔로잉 목록

SELECT MEM_NAME, MEM_ID, MEM_EMAIL FROM MEMBERS m WHERE MEM_ID IN (
SELECT MEM_ID FROM FOLLOW 
WHERE FOLLOWING_ID ='HIMAN'); --HIMAN 을 팔로우한 목록


-- 원본
SELECT F.FOLLOWING_ID FROM FOLLOW f ,MEMBERS M
WHERE F.MEM_ID =M.MEM_ID AND F.MEM_ID ='HIMAN';-- HIMAN 로그인한  ID 의 팔로잉 목록

SELECT F.MEM_ID FROM FOLLOW F,MEMBERS M
WHERE F.FOLLOWING_ID ='HIMAN' AND M.MEM_ID =F.MEM_ID  --HIMAN 을 팔로우한 목록
